version: '3.1'

services:
  django:
    container_name: simple_lms
    build: .
    volumes:
      - ./code:/code
    ports:
      - "8011:8000"
    # command: sleep infinity
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    container_name: simple_db
    image: postgres:16.3
    environment:
      POSTGRES_DB: simple_lms
      POSTGRES_USER: simple_user
      POSTGRES_PASSWORD: simple_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    